#!/bin/bash
if [ -z $(which adb) ]; then
    echo "Error adb not found, it must be installed and in PATH."
    exit
fi

if [ -n "$(find ~/.bashrc -name '.bashrc')" ]
then
    echo "alias ansshot=\"adb shell screencap -p > ./ansshot-\`date +%Y%m%d%H%M%S\`.png"\" >> ~/.bashrc
    source ~/.bashrc
    echo Completed! Cool, now you can use ansshot command
else
    echo "Error .bashrc not found"
    exit
fi
